services:
  app:
    build: . 
    container_name: shopgram
    ports:
      - 3390:3000
    restart: always
    networks:
      - default
    env_file:
      - .env

networks:
  default:
      name: shopgram-network
