version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biosell
    ports:
      - "3390:3000"
    restart: always
    networks:
      - biosell-network
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  biosell-network:
    name: biosell-network
    driver: bridge
